### ISSUE TITLE
https://medium.com/trainingcenter/webassembly-a-jornada-compiladores-jit-eef572899b5c

### ISSUE THREAD

**Issue by felipeblini** [dev-pp/weekly#1]
parte 2 da série WebAssembly, a jornada.

**Comment by felipeblini** [comment]
https://imasters.com.br/desenvolvimento/como-estimar-o-esforco-de-desenvolvimento-de-software-e-por-que-isso-e-tao-dificil-parte-01/?utm_source=iMasters&utm_campaign=fcc0374307-EMAIL_CAMPAIGN_2017_11_27&utm_medium=email&utm_term=0_c1528e6ab3-fcc0374307-359241617

**Comment by felipeblini** [comment]
https://medium.com/code-prestige/alinhamento-com-css-centralizar-%C3%A9-sempre-um-saco-21c5d78cbeac?ct=t(BrazilJS_Weekly_468_9_2013)

**Comment by felipeblini** [comment]
https://medium.com/trainingcenter/webassembly-a-jornada-compiladores-jit-eef572899b5c?ct=t(BrazilJS_Weekly_468_9_2013)

**Comment by felipeblini** [comment]
https://medium.com/@vitorleonel/m%C3%A9todos-every-e-some-do-javascript-d1a8a2327960?ct=t(BrazilJS_Weekly_468_9_2013)

**Comment by felipeblini** [comment]
http://docusaurus.io/?ct=t(BrazilJS_Weekly_468_9_2013)
Ferramenta criada pelo Facebook para facilitar a criação de sites/documentações de projetos open source.

**Comment by felipeblini** [comment]
https://www.smashingmagazine.com/2018/01/understanding-sizing-css-layout/?utm_campaign=CSS%2BLayout%2BNews&utm_medium=email&utm_source=CSS_Layout_News_129
Entendendo Sizing no CSS

**Comment by felipeblini** [comment]
https://scotch.io/tutorials/how-to-build-a-realtime-chat-app-with-react-and-graphql?utm_source=newsletter&utm_medium=email&utm_campaign=build_a_real_time_chat_app_with_react_and_graphql&utm_term=2018-01-25
How to Build a Realtime Chat App with React and GraphQL

**Comment by felipeblini** [comment]
Curso completo e gratuito de Node.js (em inglês)

Gain the ability to do build real applications in Node.JS by taking this course! Get answers from an experienced IT expert to every single question you have related to the learning you do in this course, inclucing using MongoDB, Express and Mongoose!

https://academy.learnstartup.net/p/B1fnJJEtl/the-complete-nodejs-course-build-a-full-business-rating-app/?utm_source=1

**Comment by felipeblini** [comment]
#tutoriais

Como criar um app React consumindo um back-end Node com Express
Aprenda de maneira simples a criar um front com React consumindo uma API com Node.js 

https://medium.com/code-prestige/como-criar-um-app-react-consumindo-um-back-end-node-com-express-5030e1727ace?ct=t(DevPP)

**Comment by felipeblini** [comment]
#links

Atomic Design com React

How the Atomic Design methodology allowed me to create a great design system from scratch and made me a better developer, with principles of componentization, hierarchies and reuses of code.
https://codeburst.io/atomic-design-with-react-e7aea8152957

**Comment by renanpupin** [comment]
The Brutal Lifecycle of JavaScript Frameworks
https://stackoverflow.blog/2018/01/11/brutal-lifecycle-javascript-frameworks

#javascript

**Comment by renanpupin** [comment]
How to start in JavaScript in 2018 - From beginner to Full-Stack
http://fullstackengine.net/how-to-start-in-javascript-2018/

**Comment by felipeblini** [comment]
#eventos

UX Conf BR

UNIRITTER - PORTO ALEGRE
18 de Maio de 2018

http://www.uxconf.com.br/?utm_source=devpp&utm_campaign=4e52581f7b-EMAIL_CAMPAIGN_2017_11_29&utm_medium=email&utm_term=0_c1528e6ab3-4e52581f7b-359241617

**Comment by felipeblini** [comment]
#eventos

20º Encontro Locaweb

Eventos com 5 salas simultâneas repleto de conteúdos, novidades e tendências para ajudar empreendedores e profissionais de internet a desenvolverem histórias.
11 de Maio de 2018

http://eventos.locaweb.com.br/proximos-eventos/20o-encontro-locaweb-sao-paulo/

**Comment by felipeblini** [comment]
#eventos

http://www.devcamp.com.br/
10-08-2018

**Comment by felipeblini** [comment]
#eventos 

Front in Sampa

**Comment by felipeblini** [comment]
#links

Alguns novos recursos do ES7 + ES8
A linguagem JavaScript realmente melhorou nos últimos anos, graças, em parte, a frameworks JavaScript que pressionam os limites e provam o quão importante uma funcionalidade pode ser.

https://braziljs.org/blog/alguns-novos-recursos-es7-es8/?ct=t(devpp)

**Comment by felipeblini** [comment]
#links

Funcionalidades do Vue.js do zero ao avançado ensinado pelo próprio criador da biblioteca (em inglês)
Evan You, o criador do Vue.js criou esse curso do Frontend Masters ensinando como criar aplicações de grande porte usando a biblioteca.

https://frontendmasters.com/courses/advanced-vue/

**Comment by felipeblini** [comment]
#links

8 dicas para construir aplicativos React incríveis em 2018 (em inglês)
New year, better code: mind these React.js best practices to improve the quality of your code.

https://blog.risingstack.com/8-tips-to-build-better-react-apps-in-2018/?utm_source=RisingStack+Engineering&utm_campaign=8ae06f62ed-EMAIL_CAMPAIGN_2018_01_24&utm_medium=email&utm_term=0_02a6a69990-8ae06f62ed-474933717

**Comment by felipeblini** [comment]
https://blog.angular.io/angular-5-2-now-available-312d1099bd81

**Comment by felipeblini** [comment]
https://javascriptreport.com/the-ultimate-guide-to-javascript-frameworks/

**Comment by felipeblini** [comment]
https://css-tricks.com/using-css-clip-path-create-interactive-effects/?utm_campaign=CSS%2BLayout%2BNews&utm_medium=email&utm_source=CSS_Layout_News_130

**Comment by renanpupin** [comment]
https://blog.jetbrains.com/dotnet/2018/01/17/simultaneous-debugging-javascript-net-code-rider/

**Comment by renanpupin** [comment]
https://www.youtube.com/watch?v=Wi47FoKVGsE

**Comment by felipeblini** [comment]
#tutoriais

chat room app using React, Redux, and Web Sockets
https://www.youtube.com/watch?v=x_fHXt9V3zQ

**Comment by felipeblini** [comment]
#links 

Bulma: CSS framework you should consider in 2018
By Mateusz - January 30, 201814514 4

https://matwrites.com/bulma-css-framework-for-2018/?utm_source=frontendfocus&utm_medium=email

**Comment by felipeblini** [comment]
#links

The First Complete Collection of Angular Components

https://www.grapecity.com/en/angular?utm_source=FrontEndFocus&utm_medium=Newsletter&utm_campaign=Wijmo_01-18

**Comment by felipeblini** [comment]
#links

Remova css nao utulizados

https://www.purgecss.com/

**Comment by felipeblini** [comment]
#tutoriais

https://imasters.com.br/desenvolvimento/traduzindo-funcoes-com-entityframework-core/?utm_source=iMasters&utm_campaign=3db1ae8dd9-EMAIL_CAMPAIGN_2017_11_27&utm_medium=email&utm_term=0_c1528e6ab3-3db1ae8dd9-359241617

**Comment by felipeblini** [comment]
#link

https://imasters.com.br/desenvolvimento/como-estimar-o-esforco-de-desenvolvimento-de-software-e-por-que-isso-e-tao-dificil-parte-01/?utm_source=iMasters&utm_campaign=fcc0374307-EMAIL_CAMPAIGN_2017_11_27&utm_medium=email&utm_term=0_c1528e6ab3-fcc0374307-359241617

**Comment by felipeblini** [comment]
#tutoriais

https://imasters.com.br/desenvolvimento/traduzindo-funcoes-com-entityframework-core/?utm_source=iMasters&utm_campaign=3db1ae8dd9-EMAIL_CAMPAIGN_2017_11_27&utm_medium=email&utm_term=0_c1528e6ab3-3db1ae8dd9-359241617

**Comment by felipeblini** [comment]
#eventos
Scrum - 17/02
https://www.facebook.com/events/1998258960451362/?notif_t=event_aggregate&notif_id=1517487278620612

**Comment by felipeblini** [comment]
Mudando para GraphQL na Bustle

https://www.infoq.com/br/news/2018/02/graphql-serverless-bustle

**Comment by felipeblini** [comment]
Arquitetura e microsserviços comparada à arquitetura monolítica

https://imasters.com.br/desenvolvimento/arquitetura-e-microsservicos-comparada-arquitetura-monolitica/?utm_source=iMasters&utm_campaign=2ade9ecd2e-EMAIL_CAMPAIGN_2017_11_27&utm_medium=email&utm_term=0_c1528e6ab3-2ade9ecd2e-359241617

**Comment by felipeblini** [comment]
SOLID com PHP

https://imasters.com.br/desenvolvimento/solid-com-php/?utm_source=iMasters&utm_campaign=2ade9ecd2e-EMAIL_CAMPAIGN_2017_11_27&utm_medium=email&utm_term=0_c1528e6ab3-2ade9ecd2e-359241617

**Comment by felipeblini** [comment]
Soluções "prontas para uso" e soluções customizadas em Frontend

https://www.sitepoint.com/front-end-frameworks-custom-vs-ready-use-solutions/?utm_source=frontendfocus&utm_medium=email

**Comment by renanpupin** [comment]
https://www.developer-tech.com/news/2018/jan/11/react-most-popular-front-end-javascript-framework-preact-fastest-growing/

**Comment by renanpupin** [comment]
https://www.developer-tech.com/news/2017/dec/13/facebooks-ar-studio-developers/

**Comment by renanpupin** [comment]
https://mashable.com/2018/02/23/javascript-bundle-class-course-ebook-sale/

**Comment by renanpupin** [comment]
https://dev.to/kepta/promising-promise-tips--c8f

**Comment by renanpupin** [comment]
https://medium.com/containers-on-aws/building-a-socket-io-chat-app-and-deploying-it-using-aws-fargate-86fd7cbce13f

**Comment by renanpupin** [comment]
http://voidcanvas.com/nodejs-event-loop/

**Comment by renanpupin** [comment]
https://blog.sessionstack.com/how-javascript-works-the-building-blocks-of-web-workers-5-cases-when-you-should-use-them-a547c0757f6a

**Comment by renanpupin** [comment]
https://thenewstack.io/talking-wasm-paul-milham-webassembly-may-reinvent-write-ship-code-web/
