### ISSUE TITLE
Adobe concretiza a compra da Magento

### ISSUE THREAD

**Issue by igor-imaginemage** [dev-pp/weekly#134]
No último dia 19 foi concretizada a compra da Magento Inc. pela Adobe (https://magento.com/blog/magento-news/magento-is-now-part-of-adobe).

As negociações já haviam sido reveladas a pouco tempo e apenas questões burocráticas estavam impedindo o anúncio oficial.

A Magento é a maior plataforma de e-commerce do Mundo e agora nas mãos da Adobe espera-se que grandes novidades estejam à caminho.

**Comment by felipeblini** [comment]
Valeu @igor-imaginemage
