### ISSUE TITLE
Wexflow: Open source workflow engine in C#

### ISSUE THREAD

**Issue by felipealbuquerq** [dev-pp/weekly#209]
https://www.codeproject.com/Articles/1164009/Wexflow-Open-source-workflow-engine-in-Csharp

**Comment by felipeblini** [comment]
coloca uma descrição por favor

**Comment by felipealbuquerq** [comment]
Sabe aquelas rotinas automáticas que envolvem regras?

Essas rotinas ficam mais fáceis dentro de um workflow, mas criar uma engine assim não é tarefa simples. Temos com o Wexflow algo que já foi validado em grandes empresas de GED do Brasil e do mundo e que ainda por cima é Open Source s2. 

Ta esperando o que pra começar a testar essa belezinha?
