### ISSUE TITLE
.NET Design Reviews GitHub Triage and Span(of T) Consistency

### ISSUE THREAD

**Issue by fulviocanducci** [dev-pp/weekly#22]
Assistam, muito interessante revisão de desenvolvimento da Arquitetura .NET `Span<T>`

https://www.youtube.com/watch?v=RsNFSBH3XX0&feature=push-lsb&attr_tag=wvYYh9R79BU6M5cw-6

Link relacionado:

https://medium.com/@renato.groffe/novidades-do-c-7-3-parte-3-read-only-structs-e-o-tipo-span-t-3ec096ea3da4

**Comment by felipeblini** [comment]
Oi @fulviocanducci posso usar o link do medium? Qual seria o titulo e a descricao para o conteudo do medium?

**Comment by fulviocanducci** [comment]
Pode utilizar creditando o autor Renato Groffe (que é um MVP da Microsoft)

_Titulo:_ **Novidades do C# 7.2 - parte 3: read-only structs e o tipo Span<T>**

@felipeblini  sem problemas!

**Comment by felipeblini** [comment]
Blza! Valeu
