### ISSUE TITLE
Criando um Webservice RESTful com Node.js, Restify e MySQL 

### ISSUE THREAD

**Issue by eduardolops** [dev-pp/weekly#24]
Gostaria de recomendar para a próxima weekly o mini curso do vedovelli uma referência na comunidade laravel e vuejs sobre a criação de um api restful em nodejs com mysql.

https://www.youtube.com/watch?v=MAcCWy8T-1Q&list=PLFJmwzuHdBRTBbkyH0gATtDhj6ikOIkMy

**Comment by felipeblini** [comment]
enviado, obrigado manoww
