### ISSUE TITLE
Javascript: Mas afinal, o que são closures?

### ISSUE THREAD

**Issue by eduardolops** [dev-pp/weekly#27]
As vezes pode ser um assunto que causa muita confusão, mas o texto vem explicando que são e como usa-las.

https://medium.com/@stephanowallace/javascript-mas-afinal-o-que-s%C3%A3o-closures-4d67863ca9fc

**Comment by felipealbuquerq** [comment]
Obrigado pela contribuição @eduardolops !!

**Comment by eduardolops** [comment]
vlw @felipealbuquerq  vamos que vamos
