### ISSUE TITLE
Criando aplicações node em 30 segundos com noderize

### ISSUE THREAD

**Issue by felipealbuquerq** [dev-pp/weekly#91]
https://imasters.com.br/front-end/javascript/aplicacoes-node-em-30-segundos-com-o-noderize/

**Comment by felipeblini** [comment]
O ecossistema do JavaScript cresceu muito nos últimos anos e ficou complexo. Não é raro o profissional perder horas de trabalho só para montar o esqueleto (e ambiente de desenvolvimento) do projeto. O Noderize pode nos ajudar com isso.
